// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxc__vykYRskVksflaxoskdVXJ6e2fUW4',
    appId: '1:812517675089:web:0fe11bcd1304496b7b2870',
    messagingSenderId: '812517675089',
    projectId: 'turide-aggregator',
    authDomain: 'turide-aggregator.firebaseapp.com',
    storageBucket: 'turide-aggregator.firebasestorage.app',
    measurementId: 'G-YZTHRLEF1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEF5gBhMOahBb_pWTvYqr6bKyUKlq7rWY',
    appId: '1:812517675089:android:304a7cf91b17d0877b2870',
    messagingSenderId: '812517675089',
    projectId: 'turide-aggregator',
    storageBucket: 'turide-aggregator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPsY40q4VOaQY3IyWZ0zD0bOtcCu6OUY',
    appId: '1:812517675089:ios:fde6a127953b3ff47b2870',
    messagingSenderId: '812517675089',
    projectId: 'turide-aggregator',
    storageBucket: 'turide-aggregator.firebasestorage.app',
    iosBundleId: 'com.example.turideAggregator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTPsY40q4VOaQY3IyWZ0zD0bOtcCu6OUY',
    appId: '1:812517675089:ios:fde6a127953b3ff47b2870',
    messagingSenderId: '812517675089',
    projectId: 'turide-aggregator',
    storageBucket: 'turide-aggregator.firebasestorage.app',
    iosBundleId: 'com.example.turideAggregator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxc__vykYRskVksflaxoskdVXJ6e2fUW4',
    appId: '1:812517675089:web:2c7c900bf297c5cf7b2870',
    messagingSenderId: '812517675089',
    projectId: 'turide-aggregator',
    authDomain: 'turide-aggregator.firebaseapp.com',
    storageBucket: 'turide-aggregator.firebasestorage.app',
    measurementId: 'G-V78JBFTLEG',
  );
}
